route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 5s
  group_interval: 10s
  repeat_interval: 2m
  receiver: generic

receivers:
- name: generic
  webhook_configs:
      - url: 'http://httpecho:8888'
